Fix chrome livereload
hiddentao/gulp-server-livereload pull request #43
Opened 2016-10-26 14:37 UTC by akozhemiakin

Livereload does not work in chrome of the illegal call to the window.console.log function. Log function in chrome is context aware (sensitive to the current value of 'this'). This commit fixes this chrome related bug by calling window.console.log directly, and hence in the right context.

2016-10-28 19:10 UTC, sanbor commented
This issue is affecting Chrome users. Please merge. LGTM :+1:

2016-10-30 23:24 UTC, hiddentao commented
This change was originally introduced in #41 by @SteffanDonal . I think a better fix would be:

```js
var __consoleLog = window.console.log.bind(window.console);
var __log = function(msg) {
   __consoleLog('LIVERELOAD: ' + msg);
};
```

2016-10-30 23:24 UTC, hiddentao requested changes
Please incorporate the alternative fix I've outlined. Thanks!

2016-10-30 23:50 UTC, akozhemiakin commented
Done.

2016-11-01 13:33 UTC, sanbor commented
Any update on this? Looks like @akozhemiakin applied the suggested change from @hiddentao.

2016-11-04 09:17 UTC, merged

2016-11-04 09:17 UTC, hiddentao commented
Thanks

2016-11-04 14:32 UTC, sanbor commented
Awesome, thank you!